[git_branch]
symbol = " "

[aws]
symbol = "AWS "
style = "bold white"

[conda]
symbol = "Conda "

[java]
symbol = "Java "
style = "bold 208"

[nodejs]
symbol = "Node "

[package]
symbol = " "

[python]
symbol = "Python "

[rust]
symbol = "Rust "
style = "bold 131"

[swift]
symbol = "Swift "
